<?php
defined('ELASTICSEARCH_HOST') or define('ELASTICSEARCH_HOST', '127.0.0.1');
defined('ELASTICSEARCH_PORT') or define('ELASTICSEARCH_PORT', 9200);
defined('ELASTICSEARCH_USERNAME') or define('ELASTICSEARCH_USERNAME', 'elastic');
defined('ELASTICSEARCH_PASSWORD') or define('ELASTICSEARCH_PASSWORD', '123456');